name: CD

on: [push]

env:
  FOO: bar

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set env
        run: export BAR=baz

      - name: check env
        run: env

      - name: long script
        run: |
          if [[ "foo" = "bar" ]]; then
            echo "it is"
          else
            echo "it isnt"
          fi

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
