name: CD

on: [push]

env:
  FOO: bar

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set operation environment
        run: |
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "master" ]]; then
            env="production"
          else
            env="development"
          fi
          echo "::set-env name=ENV::${env}"

      - name: check env
        run: env

      - name: check env
        run: ruby -v

#      - name: Set up Ruby 2.7
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: 2.7
