name: CD

on: [push]

env:
  FOO: bar

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set operation environment
        run: |
          echo hi
          ls fooghgh
          echo testing fail fast
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "master" ]]; then
            env="production"
          else
            env="development"
          fi
          echo "::set-env name=ENV::${env}"

      - name: check env
        run: env

      - name: Install Atmos
        run: gem install --no-document simplygenius-atmos
